version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    volumes:
      - .:/app
    networks:
      - services-network

networks:
  services-network:
    external: true
